# Generated by Django 4.1 on 2022-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
